211 ard attributes gen
insightsengineering/cards pull request #238
Opened 2024-04-30 01:54 UTC by rparmm

**What changes are proposed in this pull request?**
* Converted `ard_attributes` into an S3 generic with a method for `data.frame` objects. (#211)

Provide more detail here as needed.

**Reference GitHub issue associated with pull request.** 
Closes #211 by converting `ard_attributes` into an S3 generic with a method for `data.frame` objects. Additionally, `default` method is added to error when any object other than `data.frame` class is passed.

--------------------------------------------------------------------------------

Pre-review Checklist (if item does not apply, mark is as complete)
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [ ] If a bug was fixed, a unit test was added.
- [ ] Code coverage is suitable for any new functions/features (generally, 100% coverage for new code): `devtools::test_coverage()`
- [ ] Request a reviewer

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`

When the branch is ready to be merged:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cards (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge" or "Rebase and merge".

2024-04-30 19:16 UTC, rparmm commented
- - -
   I have read the CLA Document and I hereby sign the CLA
   - - -

2024-05-01 14:47 UTC, ddsjoberg requested changes
@rparmm thank you for the PR! This looks great! A few requested changes. Let me know if you'd like to chat about any of them.

2024-05-01 14:47 UTC, ddsjoberg commented on R/ard_attributes.R
> +  stop("There is no method for object of class: ", paste(class(data), collapse = ", "))
```suggestion
  cli::cli_abort("There is no default method for objects of class {.cls class(x)}.", call = get_cli_abort_call())
```

2024-05-01 14:47 UTC, ddsjoberg commented on R/ard_attributes.R
> +ard_attributes <- function(data, ...) {
In other generics in the package, we name the primary argument `x` to allow us to expand in any way where `data` may be a bad descriptor of the value. Can we change to `x`?

2024-05-01 14:47 UTC, ddsjoberg commented on R/ard_attributes.R
> +#' Add variable attributes to an ARD object
I think we can keep the title simple in this case

```suggestion
#' ARD Attributes
```

2024-05-01 14:47 UTC, ddsjoberg commented on R/ard_attributes.R
>    # check inputs ---------------------------------------------------------------
Can you add a check that the `...` are empty? Just add `check_dots_empty()`

2024-05-01 14:47 UTC, ddsjoberg commented on R/ard_attributes.R
>    # check inputs ---------------------------------------------------------------
There is a `check_data_frame()` call that we can remove since the s3 method ensures its class

2024-05-01 14:47 UTC, ddsjoberg commented on R/ard_attributes.R
>  #'   Default is `NULL`
What you have here works perfectly well. But my preference for organization is to have all the roxygen comments at the top of the file.

We can just keep this bit as

```r
#' @rdname ard_attributes
#' @export
```

2024-05-02 18:57 UTC, ddsjoberg approved these changes
this is great! thank you @rparmm !!

2024-05-02 18:57 UTC, merged