357 stat methods vignette
insightsengineering/cards pull request #365
Opened 2024-12-12 10:55 UTC by jtalboys

**What changes are proposed in this pull request?**

#357 Add an article detailing how a user can implement their own statistical methods

I'll open this as a draft for now as it would be good just to get a review on the content initially if you have time @ddsjoberg?

Also a couple of points/questions:
* Currently I've left in the `{cardx}` example, which would mean adding `{cardx}` to Suggests. I'm happy to remove, just couldn't remember exactly what we agreed on in the last meeting.
* I haven't been able render due to `as_cards_fn` being new and installation restrictions on our SCE - if this is important then I should be able to work around it to render the article
* Added as an article rather than a vignette
* Are there any other parts of the process which change for adding documentation like this. (If there are then I can also add to the CONTRIBUTING guidelines)

closes #357 

--------------------------------------------------------------------------------

Pre-review Checklist (if item does not apply, mark is as complete)
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] PR branch has pulled the most recent updates from master branch: `usethis::pr_merge_main()`
- [ ] If a bug was fixed, a unit test was added.
- [ ] Code coverage is suitable for any new functions/features (generally, 100% coverage for new code): `devtools::test_coverage()`
- [ ] Request a reviewer

Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] If a bug was fixed, a unit test was added.
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features: `devtools::test_coverage()`

When the branch is ready to be merged:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cards (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] **All** GitHub Action workflows pass with a :white_check_mark:
- [ ] Approve Pull Request
- [ ] Merge the PR. Please use "Squash and merge" or "Rebase and merge".

2024-12-12 10:56 UTC, jtalboys commented
Even just creating this PR I can see there's some grammar/spellings that need fixing - I'll do another pass to fix all that but please let me know if the content is what we're after @ddsjoberg @bzkrouse

2025-01-08 05:46 UTC, ddsjoberg requested changes
This is looking great!

Just a few initial comments

2025-01-08 05:46 UTC, ddsjoberg commented on vignettes/articles/creating-ards-for-stats-methods.Rmd
> +The basic functions offered by {cards} can create a wide variety of ARDs. However, sometimes we may need to include the outputs from more complicated statistical methods in our ARDs. In this article
Can we put each sentence on a new line? It makes it easier to track changes to the article in the future.

2025-01-08 05:46 UTC, ddsjoberg commented on vignettes/articles/creating-ards-for-stats-methods.Rmd
> +Over 100 different statistical methods implemented in R are able to be 'tidied' using `broom::tidy`. However, the method you aim to use might not be, or the current `broom::tidy` implementation might
Should we make the distinction that only `broom::tidy()` methods that return a single row of results work here?

2025-01-08 05:46 UTC, ddsjoberg commented on vignettes/articles/creating-ards-for-stats-methods.Rmd
> +```{r wilcox-function}
Would this be easier to read as `wilcox_one_var <- \(x) wilcox.test(x)[c("method", "p.value")]`

2025-01-31 11:34 UTC, cicdguy commented
@ddsjoberg - thanks to @pawelru, any `Config/Needs/website` dependencies will now get installed during the `pkgdown` workflow execution.

2025-01-31 16:46 UTC, daniel-woodie commented on vignettes/articles/creating-ards-for-stats-methods.Rmd
> +    statistic = everything() ~ list(t_test = \(x) t.test(x) |> broom::tidy())
As a developer looking to implement the lessons from this article, my only nudge is to expand on what's actually happening with the syntax for the `statistic` parameter. Would you be opposed to including a few sentences explaining what the code is doing along the lines of:  "The core of statistic parameter is `t.test(x)` which is using the defaults of the t.test function to run a one-sample t-test against a null mean of 0. This is being piped into broom::tidy() which creates the required format for cards. This is all nested in a named list...". My understanding of what's going on with this line kind of falls apart from here.

2025-01-31 17:38 UTC, ddsjoberg commented
@jtalboys it looks like the only calls to pharmaverseadam dataset are in ADSL. Can we just use the ADSL dataset that ships with the cards package instead?

2025-01-31 18:43 UTC, ddsjoberg commented
> @jtalboys it looks like the only calls to pharmaverseadam dataset are in ADSL. Can we just use the ADSL dataset that ships with the cards package instead?

FYI I updated to use `cards::ADSL` so we didn't introduce an unnecessary dependency

2025-01-31 21:21 UTC, ddsjoberg commented on vignettes/articles/creating-ards-for-stats-methods.Rmd
> +    statistic = everything() ~ list(t_test = \(x) t.test(x) |> broom::tidy())
That's a great suggestion, thanks @daniel-woodie !

@jtalboys can you add more detail around this? I think including the following could be
- typically, users will pass a function that returns a scalar value
- but the function also allows for functions that return named lists. the names from the named list will be used as the statistic names
- since a data frame/tibble is just a named list, the function can also return a data frame/tibble

2025-02-11 15:56 UTC, bzkrouse commented on vignettes/articles/creating-ards-for-stats-methods.Rmd
> +As mentioned above, we need to define a function which carries out or required statistical method and outputs a named list of the information we wish to include in the ARD.
```suggestion
As mentioned above, we need to define a function which carries out our required statistical method and outputs a named list of the information we wish to include in the ARD.
```

2025-02-11 15:59 UTC, bzkrouse approved these changes
great addition! just a small typo fix :)

2025-02-13 15:22 UTC, ddsjoberg commented
Thanks @jtalboys ! Let us know when these is ready to merge, and we'll get started with our release cycle! 👯

2025-02-13 15:28 UTC, jtalboys commented
I think we're good to go! Thanks for the reviews @ddsjoberg , @bzkrouse !!

2025-02-13 16:54 UTC, ddsjoberg approved these changes
Awesome, thank you @jtalboys !!

2025-02-13 16:55 UTC, merged